In [1]:
import pandas as pd

# Read the CSV file
df = pd.read_csv('student-mat.csv', sep=';')

# Display the first few rows of the DataFrame
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [7]:
df['failures'].value_counts()

failures
0    312
1     50
2     17
3     16
Name: count, dtype: int64

In [2]:
df['sex'].value_counts()

sex
F    208
M    187
Name: count, dtype: int64

In [3]:
import json
json_data = json.loads(df.to_json(orient='records'))
json_data[:5]

[{'school': 'GP',
  'sex': 'F',
  'age': 18,
  'address': 'U',
  'famsize': 'GT3',
  'Pstatus': 'A',
  'Medu': 4,
  'Fedu': 4,
  'Mjob': 'at_home',
  'Fjob': 'teacher',
  'reason': 'course',
  'guardian': 'mother',
  'traveltime': 2,
  'studytime': 2,
  'failures': 0,
  'schoolsup': 'yes',
  'famsup': 'no',
  'paid': 'no',
  'activities': 'no',
  'nursery': 'yes',
  'higher': 'yes',
  'internet': 'no',
  'romantic': 'no',
  'famrel': 4,
  'freetime': 3,
  'goout': 4,
  'Dalc': 1,
  'Walc': 1,
  'health': 3,
  'absences': 6,
  'G1': 5,
  'G2': 6,
  'G3': 6},
 {'school': 'GP',
  'sex': 'F',
  'age': 17,
  'address': 'U',
  'famsize': 'GT3',
  'Pstatus': 'T',
  'Medu': 1,
  'Fedu': 1,
  'Mjob': 'at_home',
  'Fjob': 'other',
  'reason': 'course',
  'guardian': 'father',
  'traveltime': 1,
  'studytime': 2,
  'failures': 0,
  'schoolsup': 'no',
  'famsup': 'yes',
  'paid': 'no',
  'activities': 'no',
  'nursery': 'no',
  'higher': 'yes',
  'internet': 'yes',
  'romantic': 'no',
  'famrel': 5,
  'freetime': 3,
  'goout': 3,
  'Dalc': 1,
  'Walc': 1,
  'health': 3,
  'absences': 4,
  'G1': 5,
  'G2': 5,
  'G3': 6},
 {'school': 'GP',
  'sex': 'F',
  'age': 15,
  'address': 'U',
  'famsize': 'LE3',
  'Pstatus': 'T',
  'Medu': 1,
  'Fedu': 1,
  'Mjob': 'at_home',
  'Fjob': 'other',
  'reason': 'other',
  'guardian': 'mother',
  'traveltime': 1,
  'studytime': 2,
  'failures': 3,
  'schoolsup': 'yes',
  'famsup': 'no',
  'paid': 'yes',
  'activities': 'no',
  'nursery': 'yes',
  'higher': 'yes',
  'internet': 'yes',
  'romantic': 'no',
  'famrel': 4,
  'freetime': 3,
  'goout': 2,
  'Dalc': 2,
  'Walc': 3,
  'health': 3,
  'absences': 10,
  'G1': 7,
  'G2': 8,
  'G3': 10},
 {'school': 'GP',
  'sex': 'F',
  'age': 15,
  'address': 'U',
  'famsize': 'GT3',
  'Pstatus': 'T',
  'Medu': 4,
  'Fedu': 2,
  'Mjob': 'health',
  'Fjob': 'services',
  'reason': 'home',
  'guardian': 'mother',
  'traveltime': 1,
  'studytime': 3,
  'failures': 0,
  'schoolsup': 'no',
  'famsup': 'yes',
  'paid': 'yes',
  'activities': 'yes',
  'nursery': 'yes',
  'higher': 'yes',
  'internet': 'yes',
  'romantic': 'yes',
  'famrel': 3,
  'freetime': 2,
  'goout': 2,
  'Dalc': 1,
  'Walc': 1,
  'health': 5,
  'absences': 2,
  'G1': 15,
  'G2': 14,
  'G3': 15},
 {'school': 'GP',
  'sex': 'F',
  'age': 16,
  'address': 'U',
  'famsize': 'GT3',
  'Pstatus': 'T',
  'Medu': 3,
  'Fedu': 3,
  'Mjob': 'other',
  'Fjob': 'other',
  'reason': 'home',
  'guardian': 'father',
  'traveltime': 1,
  'studytime': 2,
  'failures': 0,
  'schoolsup': 'no',
  'famsup': 'yes',
  'paid': 'yes',
  'activities': 'no',
  'nursery': 'yes',
  'higher': 'yes',
  'internet': 'no',
  'romantic': 'no',
  'famrel': 4,
  'freetime': 3,
  'goout': 2,
  'Dalc': 1,
  'Walc': 2,
  'health': 5,
  'absences': 4,
  'G1': 6,
  'G2': 10,
  'G3': 10}]

In [4]:
import json

# Print the body JSON object
# Read the veracity-config.json file
with open('veracity-config.json') as file:
    config = json.load(file)

# Create the body JSON object
body_json = {
    'data': json_data,
    'config': config,
}

In [5]:
import requests

url = 'http://localhost:3000/checks'
headers = {'Content-Type': 'application/json'}
response = requests.post(url, json=body_json, headers=headers)

print(response.status_code)
print(response.text)  # print raw response text

200
{"processId":"39b520f1-b0c1-4571-90a4-2b861dcd3b77"}

In [6]:
import json
url = 'http://localhost:3000/checks/:id'

if response.status_code == 200:
    process_id = json.loads(response.text)['processId']
    print(process_id)
    url_with_id = url.replace(':id', process_id)
    response_with_id = requests.get(url_with_id)
    print(response_with_id.status_code)
    pretty_response = json.dumps(json.loads(response_with_id.text), indent=4)
    print(pretty_response)
else:
    print("Error: Status code is not 200")

39b520f1-b0c1-4571-90a4-2b861dcd3b77
200
{
    "status": "Done",
    "result": {
        "problems": [
            {
                "target": "/0/failures",
                "message": "must be >= 1"
            },
            {
                "target": "G3 mean",
                "message": "'< 3' not satisfied"
            }
        ],
        "time": 35
    }
}